### ISSUE TITLE
When cancelling on the payment page, you get a "thank you for your purchase" message in Magento

### ISSUE THREAD

**Issue by hostep** [mollie/magento2#10]
Using Magento CE 2.1.4 and v0.9.7 of the Mollie M2 module.

When you go from the checkout in Magento to the payment page of Mollie and then cancel over there, as a customer you get the following message in Magento: "Thank you for your purchase" (or something like that). Even though the order has been cancelled when looking in the Magento backend.

So the message to the customer should be something else in this case I believe, otherwise the customer will be very confused :)

**Comment by robin-mollie** [comment]
Hi, @hostep,

Sounds like this is related to #6, which is currently being worked on. We'll make sure to update this issue when we know more :)

**Comment by Magmodules** [comment]
Fixed in 0.9.8

**Comment by epicglows** [comment]
Updated to 0.9.8 but customer still receives an order confirmation e-mail when cancelling in the payment sreen.

**Comment by epicglows** [comment]
Updated to 0.9.8 but customer still gets an order confirmation e-mail when cancelling in the Mollie payment screen

**Comment by Magmodules** [comment]
Order emails are sent after the order has been placed and before it is redirected to Mollie, this is not related to this issue. This is the standard process in Magento 2. We can look into this issue in a next release.

**Comment by epicglows** [comment]
I do think that it's pretty important that when a customer cancels payment, he doesn't get an order confirmation e-mail - This looks strange and can be very confusing for customers in my opinion. This shouldn't be standard Magento2 behaviour since it works fine with any other payment methods like PayPal and with other external payment providers. Hopefully you're able to look into this issue with priority.

**Comment by Magmodules** [comment]
Not saying it is not important ;) Will update this in the upcoming v1.0.0 release, thnx for the report.

**Comment by epicglows** [comment]
Thank you - Any ETA for this? :)

**Comment by Magmodules** [comment]
Somewhere this week, need to do some extra testing for this

**Comment by Magmodules** [comment]
Added/fixed in v1.0.0
