### ISSUE TITLE
Missing svg file reference of qr-code option in Mollie

### ISSUE THREAD

**Issue by jesse-deboer** [mollie/magento2#322]
**Describe the bug**
When using GraphQL to query the available issuers I get the following response:
`Undefined index: svg in /mollie/magento2/Service/Mollie/GetIssuers.php on line 96
`

This is because there is no reference to the svg file available for the QR-code option with iDeal.

**Used versions**
- *Magento Version 2.3.4*

**To Reproduce**
Make the following query in Magento:

```
query { 
  cart(cart_id: "") {
    available_payment_methods {
     	mollie_available_issuers {
      	 code
      	 image
      	 name
    	 svg
    	} 
    }
  }
}
```

**Expected behavior**
GraphQL should send back all the names, codes, png's and svg's

**Actual behavior**
Undefined index: svg in /mollie/magento2/Service/Mollie/GetIssuers.php on line 96 because of a missing svg

**Comment by Frank-Magmodules** [comment]
@jesse-deboer ,
Thank you for this [PR](https://github.com/mollie/magento2/pull/323), it seems that the .SVG file is missing in your [PR](https://github.com/mollie/magento2/pull/323) as well in our repository but I do think it's a good idea to change all the .PNG's to .SVG's so we have created an internal task to review your PR and merge it into our next release. Many thanks for your contribution to this!

**Comment by Frank-Magmodules** [comment]
Hi @jesse-deboer,
We are happy to share that we've just released the new [1.19.0](https://github.com/mollie/magento2/releases/tag/v1.19.0) version where we've switched to SVG images completely. As the SVG file itself was missing in your [PR](https://github.com/mollie/magento2/pull/323) we could not use it but it was a good trigger to implement SVG images overall.  We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by jesse-deboer** [comment]
@Frank-Magmodules

This is still an issue, the update doesn't change anything for the GraphQL API. The images are loaded external from Mollie and GraphQL is now giving an error still because it needs an 'svg' due to GetIssuers.php and schema.graphqls

See pull request #330
