### ISSUE TITLE
Multiple cancel actions performed when payment using klarna pay later fails

### ISSUE THREAD

**Issue by JeroenVanLeusden** [mollie/magento2#372]
**Describe the bug**
Multiple cancel actions performed when payment using klarna pay later fails. 

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.5-p2
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 1.23.1

**To Reproduce**
Unknown. Tried reproducing it using the test environment but no luck yet.

**Expected behavior**
Only one cancel action is processed.

**Actual behavior**
Two cancel actions are processed. This also results in two canceled reservations making the salable qty go up and let's you oversell.

**Screenshots**
Magento order comment:
![Screen Shot 2021-03-24 at 12 54 54](https://user-images.githubusercontent.com/14925052/112306510-29455e00-8ca0-11eb-9d79-7469cbe37881.png)

Mollie events:
![Screenshot 2021-03-19 at 16 21 54](https://user-images.githubusercontent.com/14925052/112306707-60b40a80-8ca0-11eb-90c2-2db586ea2ba5.png)

**Additional context**
Multiple entries are written to mollie log file.
```
[2021-03-18 10:26:00] Mollie.INFO: info: 000323075 De bestelling is geannuleerd. Reden: betaling failed [] []
[2021-03-18 10:26:00] Mollie.INFO: success: {"success":false,"status":"failed","order_id":"173467","type":"success","method":"Klarna Pay Later"} [] []

[2021-03-18 10:26:01] Mollie.INFO: info: 000323075 De bestelling is geannuleerd. Reden: betaling failed [] []
[2021-03-18 10:26:01] Mollie.INFO: success: {"success":false,"status":"failed","order_id":"173467","type":"webhook","method":"Klarna Pay Later"} [] []
```

**Comment by JeroenVanLeusden** [comment]
Log entries i found in access.log:
```
{"time":"2021-03-24T12:31:12+00:00","request":"GET /mollie/checkout/process/?order_id=176662&payment_token=<removed>&utm_nooverride=1 HTTP/1.0", "status":"302", "body_bytes_sent":"0", "referer":"https://pay.klarna.com/", "user_agent":"Mozilla/5.0 (Linux; Android 11; SM-G981B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.90 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/310.0.0.50.118;]", "request_time":"0.713", "handler":"phpfpm", "country":"NL", "port":"8080"}
{"time":"2021-03-24T12:31:12+00:00","request":"GET /mollie/checkout/process/?order_id=176662&payment_token=<removed>&utm_nooverride=1 HTTP/2.0", "status":"302", "body_bytes_sent":"20", "referer":"https://pay.klarna.com/", "user_agent":"Mozilla/5.0 (Linux; Android 11; SM-G981B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.90 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/310.0.0.50.118;]", "request_time":"0.714", "handler":"varnish", "country":"NL", "port":"443"}
```

**Comment by JJSchaart** [comment]
@JeroenVanLeusden Can you confirm the webhook is called only once from the web logging?

**Comment by Frank-Magmodules** [comment]
HI @JeroenVanLeusden ,

Thank you for opening and reporting this issue. 
I've tried to reproduce this using a Klarna `canceled` and `failed` state but this also seems to be fine. See these screens:

![mollie-cancel](https://user-images.githubusercontent.com/24823946/112322422-2ef76f80-8cb1-11eb-95ac-835439c61972.jpg)
![mollie-fail](https://user-images.githubusercontent.com/24823946/112322427-2f900600-8cb1-11eb-93da-c04586def5bf.jpg)


But a good question from @JJSchaart as well, maybe check this first, otherwise, I suspect there is something else going into this process.

**Comment by JeroenVanLeusden** [comment]
@Frank-Magmodules 

Access log seems to be fine. Two entries are logged because of varnish I guess. Orders with only only cancellation also show two entries.
```
{"time":"2021-03-24T14:06:01+00:00", "remote_user":"", "request":"GET /mollie/checkout/process/?order_id=176764&payment_token=<removed>&utm_nooverride=1 HTTP/1.0", "status":"302", "body_bytes_sent":"0", "referer":"https://pay.klarna.com/eu/payments/<removed>", "user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1", "request_time":"1.010", "handler":"phpfpm", "country":"NL", "port":"8080", "ssl_cipher":"", "ssl_protocol":""}
{"time":"2021-03-24T14:06:01+00:00", "remote_user":"", "request":"GET /mollie/checkout/process/?order_id=176764&payment_token=<removed>&utm_nooverride=1 HTTP/2.0", "status":"302", "body_bytes_sent":"20", "referer":"https://pay.klarna.com/eu/payments/<removed>", "user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1", "request_time":"1.012", "handler":"varnish", "country":"NL", "port":"443"}
```

Two stack traces:
```
2021-03-24T14:06:00+00:00 INFO (6): Order ID: 176764
2021-03-24T14:06:00+00:00 INFO (6): Order State: new
2021-03-24T14:06:00+00:00 INFO (6): #0 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Model/Client/Orders.php(386): Mollie\Payment\Helper\General->registerCancellation(Object(Magento\Sales\Model\Order\Interceptor), 'failed')
#1 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Model/Mollie.php(382): Mollie\Payment\Model\Client\Orders->processTransaction(Object(Magento\Sales\Model\Order\Interceptor), Object(Mollie\Api\MollieApiClient), 'success', '0hdKbA4NUNqbyvC...')
#2 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Controller/Checkout/Process.php(78): Mollie\Payment\Model\Mollie->processTransaction('176764', 'success', '0hdKbA4NUNqbyvC...')
#3 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Action/Action.php(108): Mollie\Payment\Controller\Checkout\Process->execute()
#4 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(138): Mollie\Payment\Controller\Checkout\Process\Interceptor->___callParent('dispatch', Array)
#6 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(153): Mollie\Payment\Controller\Checkout\Process\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /data/web/deployment/releases/20210318071801/generated/code/Mollie/Payment/Controller/Checkout/Process/Interceptor.php(26): Mollie\Payment\Controller\Checkout\Process\Interceptor->___callPlugins('dispatch', Array, Array)
#8 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/FrontController.php(162): Mollie\Payment\Controller\Checkout\Process\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Mollie\Payment\Controller\Checkout\Process\Interceptor))
#10 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#12 /data/web/deployment/releases/20210318071801/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /data/web/deployment/releases/20210318071801/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /data/web/deployment/releases/20210318071801/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#18 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->launch()
#20 /data/web/deployment/releases/20210318071801/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#21 {main}
2021-03-24T14:06:01+00:00 INFO (6): Order ID: 176764
2021-03-24T14:06:01+00:00 INFO (6): Order State: new
2021-03-24T14:06:01+00:00 INFO (6): #0 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Model/Client/Orders.php(386): Mollie\Payment\Helper\General->registerCancellation(Object(Magento\Sales\Model\Order\Interceptor), 'failed')
#1 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Model/Mollie.php(382): Mollie\Payment\Model\Client\Orders->processTransaction(Object(Magento\Sales\Model\Order\Interceptor), Object(Mollie\Api\MollieApiClient), 'webhook', NULL)
#2 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Controller/Checkout/Webhook.php(75): Mollie\Payment\Model\Mollie->processTransaction('176764', 'webhook')
#3 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Action/Action.php(108): Mollie\Payment\Controller\Checkout\Webhook->execute()
#4 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(138): Mollie\Payment\Controller\Checkout\Webhook\Interceptor->___callParent('dispatch', Array)
#6 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(153): Mollie\Payment\Controller\Checkout\Webhook\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /data/web/deployment/releases/20210318071801/generated/code/Mollie/Payment/Controller/Checkout/Webhook/Interceptor.php(26): Mollie\Payment\Controller\Checkout\Webhook\Interceptor->___callPlugins('dispatch', Array, Array)
#8 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/FrontController.php(162): Mollie\Payment\Controller\Checkout\Webhook\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Mollie\Payment\Controller\Checkout\Webhook\Interceptor))
#10 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#12 /data/web/deployment/releases/20210318071801/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /data/web/deployment/releases/20210318071801/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /data/web/deployment/releases/20210318071801/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#18 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->launch()
#20 /data/web/deployment/releases/20210318071801/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#21 {main}
```

Appears that the `/mollie/checkout/process` and `/mollie/checkout/webhook` is called although i cannot find a webhook entry in the access logs.

**Comment by JeroenVanLeusden** [comment]
Another stack trace with some additional request information
```
2021-03-24T15:10:13+00:00 INFO (6): Order ID: 176823
2021-03-24T15:10:13+00:00 INFO (6): Order State: new
2021-03-24T15:10:13+00:00 INFO (6): Request Path: /mollie/checkout/process/
2021-03-24T15:10:13+00:00 INFO (6): Request Method: GET
2021-03-24T15:10:13+00:00 INFO (6): Request Params: Array
(
    [order_id] => 176823
    [payment_token] => <removed>
    [utm_nooverride] => 1
)

2021-03-24T15:10:13+00:00 INFO (6): #0 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Model/Client/Orders.php(386): Mollie\Payment\Helper\General->registerCancellation(Object(Magento\Sales\Model\Order\Interceptor), 'canceled')
#1 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Model/Mollie.php(382): Mollie\Payment\Model\Client\Orders->processTransaction(Object(Magento\Sales\Model\Order\Interceptor), Object(Mollie\Api\MollieApiClient), 'success', '2QC1EdL58PaV5q2...')
#2 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Controller/Checkout/Process.php(78): Mollie\Payment\Model\Mollie->processTransaction('176823', 'success', '2QC1EdL58PaV5q2...')
#3 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Action/Action.php(108): Mollie\Payment\Controller\Checkout\Process->execute()
#4 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(138): Mollie\Payment\Controller\Checkout\Process\Interceptor->___callParent('dispatch', Array)
#6 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(153): Mollie\Payment\Controller\Checkout\Process\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /data/web/deployment/releases/20210318071801/generated/code/Mollie/Payment/Controller/Checkout/Process/Interceptor.php(26): Mollie\Payment\Controller\Checkout\Process\Interceptor->___callPlugins('dispatch', Array, Array)
#8 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/FrontController.php(162): Mollie\Payment\Controller\Checkout\Process\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Mollie\Payment\Controller\Checkout\Process\Interceptor))
#10 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#12 /data/web/deployment/releases/20210318071801/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /data/web/deployment/releases/20210318071801/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /data/web/deployment/releases/20210318071801/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#18 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->launch()
#20 /data/web/deployment/releases/20210318071801/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#21 {main}
2021-03-24T15:10:13+00:00 INFO (6): Order ID: 176823
2021-03-24T15:10:13+00:00 INFO (6): Order State: new
2021-03-24T15:10:13+00:00 INFO (6): Request Path: /mollie/checkout/webhook/
2021-03-24T15:10:13+00:00 INFO (6): Request Method: POST
2021-03-24T15:10:13+00:00 INFO (6): Request Params: Array
(
    [isAjax] => 1
    [id] => <removed>
)

2021-03-24T15:10:13+00:00 INFO (6): #0 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Model/Client/Orders.php(386): Mollie\Payment\Helper\General->registerCancellation(Object(Magento\Sales\Model\Order\Interceptor), 'canceled')
#1 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Model/Mollie.php(382): Mollie\Payment\Model\Client\Orders->processTransaction(Object(Magento\Sales\Model\Order\Interceptor), Object(Mollie\Api\MollieApiClient), 'webhook', NULL)
#2 /data/web/deployment/releases/20210318071801/vendor/mollie/magento2/Controller/Checkout/Webhook.php(75): Mollie\Payment\Model\Mollie->processTransaction('176823', 'webhook')
#3 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Action/Action.php(108): Mollie\Payment\Controller\Checkout\Webhook->execute()
#4 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(138): Mollie\Payment\Controller\Checkout\Webhook\Interceptor->___callParent('dispatch', Array)
#6 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(153): Mollie\Payment\Controller\Checkout\Webhook\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /data/web/deployment/releases/20210318071801/generated/code/Mollie/Payment/Controller/Checkout/Webhook/Interceptor.php(26): Mollie\Payment\Controller\Checkout\Webhook\Interceptor->___callPlugins('dispatch', Array, Array)
#8 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/FrontController.php(162): Mollie\Payment\Controller\Checkout\Webhook\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Mollie\Payment\Controller\Checkout\Webhook\Interceptor))
#10 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#12 /data/web/deployment/releases/20210318071801/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /data/web/deployment/releases/20210318071801/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /data/web/deployment/releases/20210318071801/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /data/web/deployment/releases/20210318071801/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#18 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /data/web/deployment/releases/20210318071801/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->launch()
#20 /data/web/deployment/releases/20210318071801/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#21 {main}
```

**Comment by Frank-Magmodules** [comment]
Hi @JeroenVanLeusden ,

Thank you for sharing the logs. 

I've internally checked this and as far as we know this issue didn’t happen before. We also checked this on our local and demo environments and it seems that the webhook comes slightly later than the process call. A possible explanation could be is that your process page is slightly slower than your webhook and though causing this error. This could be solved by using locks to prevent this, but as this is not a well-known issue we won’t add it to the extension for now.

Have a good start to the week!

**Comment by Frank-Magmodules** [comment]
Hi @JeroenVanLeusden ,

I had an internal talk about this issue and we have decided to catch this within the Mollie extension.
I wiill let you know once the new version with this addition is available! Sorry for the confusion on this.

**Comment by Frank-Magmodules** [comment]
HI @JeroenVanLeusden , we are happy to share that we've just released [ version 1.2.5](
https://github.com/mollie/magento2/releases/tag/v1.25.0) where we have added a feature to lock cancellations to prevent double cancellations like this. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by JeroenVanLeusden** [comment]
@Frank-Magmodules The issue still exists on v1.25, any information you need to debug this further?

**Comment by Frank-Magmodules** [comment]
HI @JeroenVanLeusden , strange, yes, can you please [contact us ](https://www.magmodules.eu/support-form.html)and share the environment details if possible so we can take a look with you on this?

**Comment by JJSchaart** [comment]
@Frank-Magmodules is this issue already fixed?

**Comment by Frank-Magmodules** [comment]
HI @JJSchaart , yes, as far as I know, this is not a known issue anymore in the latest version.
