### ISSUE TITLE
Order confirmations are sending twice with latest version v2.35.0

### ISSUE THREAD

**Issue by JelleGe** [mollie/magento2#749]
**Describe the bug**
The order confirmation email is sent twice with the latest version 2.35.0

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.35.0

**To Reproduce**
1. Place a order
2. Complete a payment using a Mollie payment method
3. The order confirmation email is sent twice.

**Expected behavior**
Just sending 1 confirmation email

**Comment by Frank-Magmodules** [comment]
Hello @JelleGe, thank you for opening this issue. Could you please reach out to us [directly](https://www.magmodules.eu/help) regarding this matter? 
Since I'm unable to reproduce the issue on my end, it would be helpfull for us to investigate this together.

**Comment by JelleGe** [comment]
@Frank-Magmodules Thanks for the reply. We just reverted back to 2.34.0 and the problem is solved. Will contact you directly.

**Comment by Frank-Magmodules** [comment]
Hello @JelleGe , It's great that you've successfully prevented this with the revert. We're prepared to dive deeper into this but since we're still unable to replicate the issue on our end, we're eagerly awaiting your response to collaborate on troubleshooting together. Thank you!
